# Generated by Django 5.1.3 on 2024-12-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0002_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='email',
            new_name='mail',
        ),
    ]
