# Generated by Django 5.1.3 on 2024-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0004_remove_webinar_mail_webinar_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='webinar',
            name='mail',
            field=models.EmailField(default='risheb', max_length=254),
            preserve_default=False,
        ),
    ]
