# Generated by Django 5.1.3 on 2024-12-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
