# Generated by Django 5.1.3 on 2024-12-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0010_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
