# Generated by Django 5.1.3 on 2024-12-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0013_team_bio_team_post_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.TextField(max_length=500),
        ),
    ]
