# Generated by Django 5.1.3 on 2024-12-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0014_alter_team_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
