# Generated by Django 5.1.3 on 2024-12-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0016_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=250)),
                ('phno', models.IntegerField(max_length=20)),
                ('field', models.CharField(max_length=250)),
                ('exp', models.IntegerField(max_length=20)),
            ],
        ),
    ]
