# Generated by Django 5.1.3 on 2024-12-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0017_immigration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immigration',
            name='exp',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='immigration',
            name='phno',
            field=models.BigIntegerField(),
        ),
    ]
