# Generated by Django 5.1.3 on 2025-02-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0018_alter_immigration_exp_alter_immigration_phno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Job Mode')),
                ('job_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('job_location', models.CharField(max_length=255, verbose_name='Location')),
                ('job_type', models.CharField(choices=[('internship', 'Internship'), ('full_time', 'Full-time'), ('contract', 'Contract')], max_length=50, verbose_name='Job Type')),
                ('job_exp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Experience Level')),
                ('job_details', models.TextField(verbose_name='Job Details')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
