# Generated by Django 5.1.3 on 2025-02-21 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0019_careers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careers',
            name='slug',
        ),
    ]
