# Generated by Django 5.1.3 on 2025-02-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0024_remove_jobapplication_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='resume',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
