# Generated by Django 5.1.3 on 2025-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0025_remove_jobapplication_resume_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admissionpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
