# Generated by Django 5.1.3 on 2025-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lpapp', '0026_admissionpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchisePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchisename', models.CharField(max_length=100)),
                ('franchiseemail', models.EmailField(max_length=254)),
                ('franchisephone_number', models.CharField(max_length=20)),
                ('franchisemessage', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
